version: "3.1"
services:
    database:
        image: mariadb:10.5
        container_name: project-mariadb
        working_dir: /application
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        ports:
            - "2140:3306"
    webserver:
        image: nginx:alpine
        container_name: project-webserver
        working_dir: /var/www
        volumes: # Every project is a different subdirectory in projects
            - ./projects/backend:/var/www
            - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "2137:80"
    php-fpm:
        build:
            context: ./php-fpm
        depends_on:
            - database
        container_name: project-php-fpm
        volumes: # Every project is a different subdirectory in projects
            - ./projects/backend:/var/www
