version: "3.1"
services:
    mariadb:
        image: mariadb:10.4
        container_name: project-mariadb
        working_dir: /application
        volumes:
            - ./project:/application
        environment:
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_DATABASE=baseofdata
            - MYSQL_USER=dbuser
            - MYSQL_PASSWORD=dbpass
        ports:
            - "2140:3306"
    webserver:
        image: nginx:alpine
        container_name: project-webserver
        working_dir: /application
        volumes:
            - ./project:/application
            - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "2137:80"
    php-fpm:
        build: phpdocker/php-fpm
        container_name: project-php-fpm
        working_dir: /application
        volumes:
            - ./project:/application